# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: my blog
subtitle: ''
description: '用Hexo + Butterfly搭建的个人博客'
keywords:
author: 琉璃仙
language: zh-CN
timezone: 'Asia/Shanghai'

# URL
url: https://mengxingdemeng.github.io/hexo-blog
root: /hexo-blog/
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true
  trailing_html: true

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render: demo/**/*

# Writing
new_post_name: :title.md
default_layout: post
titlecase: false
external_link:
  enable: true
  field: site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
syntax_highlighter: highlight.js
highlight:
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
meta_generator: true

# Date / Time format
date_format: YYYY-MM-DD
time_format: HH:mm:ss
updated_option: mtime

# Pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
include:
exclude:
ignore:

# Extensions
theme: butterfly

# Deployment
deploy:
  type: git
  repo: https://github.com/mengxingdemeng/hexo-blog.git
  branch: gh-pages

# # 全站加密配置
# encrypt:
#   enable: true
#   password: "hy4892694748"  # 改成你自己的全站密码，比如 123456
#   message: "🔒 请输入访问密码"
#   theme: "xray"  # 密码框样式，支持多种可选
#   wrong_pass_message: "❌ 密码错误，请重新输入"
#   wrong_hash_message: "❌ 验证失败，请刷新页面重试"
#   remember: true
#   rememberExpireDays: 1

# hexo_password:
#   enable: true
#   password: hy4892694748 # 全站密码
#   include:
#     - "**/*"  # 加密所有页面（首页、文章、归档等）
#   exclude: []