name: 更新LeetCode数据
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

# 👇 强制使用 Node 24（解决 GitHub 官方弃用问题）
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: 创建图片目录
        run: mkdir -p source/images
      
      - name: 生成LeetCode卡片
        run: |
          sudo apt-get install -y wget
          wget -O leetcard https://cdn.jsdelivr.net/gh/2754LM/leetcode-card@master/bin/leetcard-linux-amd64
          chmod +x leetcard
          ./leetcard --username "confident-varahamihiracj1" --cn --theme light --output source/images/leetcode.svg
      
      - name: 提交并推送
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add source/images/leetcode.svg
          git commit -m "Auto Update LeetCode Stats" || echo "No changes"
          git push origin master